from pydantic import BaseModel, Field
from typing import List, Optional, Dict
from enum import Enum

# ─────────────────────────────────────────────
# Canonical Enumerations
# ─────────────────────────────────────────────

class SourceModality(str, Enum):
    """
    Enumerates the origin of a proposed intent.
    The MCR uses this to distinguish trusted from untrusted input channels.
    'VISUAL_TEXT_INJECTION' is the primary adversarial modality (Trojan Signs).
    """
    VOICE_COMMAND        = "voice_command"         # From authenticated microphone/NPU
    VISUAL_OBJECT        = "visual_object"          # From camera: object detection (trusted)
    VISUAL_TEXT_INJECTION = "visual_text_injection" # From camera: text read off environment (untrusted)
    PROGRAMMATIC         = "programmatic"           # From internal code / test harness
    UNKNOWN              = "unknown"                 # Fallback — should default-VETO

class DecisionStatus(str, Enum):
    """
    The three possible outcomes of the Semantic Firewall.
    PASS  → All checks cleared, dispatch to hardware.
    WARN  → Suspicious but not definitively blocked; escalate to Human-in-the-Loop.
    VETO  → Blocked. Do not dispatch. Log the reason.
    """
    PASS = "PASS"
    WARN = "WARN"
    VETO = "VETO"

class VetoSource(str, Enum):
    """Identifies which validation engine component triggered a WARN or VETO."""
    RADIX_TREE  = "RadixTree"
    MCR         = "MCR"
    LTL         = "LTL"
    AUDIO_BRIDGE = "AudioBridge"
    EXCEPTION   = "Exception"  # Fail-safe: triggered when the engine itself crashes


# ─────────────────────────────────────────────
# CANONICAL IntentPacket
# This is the single source of truth. Every module imports from here.
# The version in main.py was a duplicate and has been removed.
# ─────────────────────────────────────────────

class IntentPacket(BaseModel):
    """
    Represents a proposed action generated by the Cloud Brain (VLA).
    Produced by brain_cloud and submitted to the Firewall's /propose_intent endpoint.
    """
    # Unique identifier for this intent — use uuid4 on the Brain side
    request_id: str

    # High-level action verb. Must match a key in the policy manifest.
    # e.g., 'move', 'pick', 'place', 'dispose', 'stop'
    action: str

    # The specific object the action targets.
    # Exact surface-form noun as identified by the VLM.
    target: str

    # Proposed 3D end-effector coordinates in robot base frame (millimeters).
    # Required — do NOT default to zero. A missing coordinate is not safe.
    coordinates: Dict[str, float] = Field(
        ...,
        description="Must include keys: x, y, z. No defaults — caller must provide."
    )

    # Confidence score from the VLM (0.0–1.0).
    confidence: float

    # Where did this intent originate? Used by MCR for modality trust scoring.
    # NEVER allow VISUAL_TEXT_INJECTION to execute high-risk actions.
    source_modality: SourceModality

    # Free-text chain-of-thought from the VLM explaining the intent.
    # Logged verbatim in the audit trail. Not used for logic gating.
    reasoning_trace: str

    # Raw transcript of the spoken command that contributed to this intent (if any).
    # Empty string if the intent has no audio component.
    raw_transcript: str = ""

    # AASL level the Brain believes this action requires (1=routine, 4=irreversible).
    # The Firewall validates this claim — a mismatch itself triggers a WARN.
    aasl_target_level: int = Field(ge=1, le=4)


# ─────────────────────────────────────────────
# VetoPacket — Firewall Response
# ─────────────────────────────────────────────

class VetoPacket(BaseModel):
    """
    The Semantic Firewall's response to a proposed IntentPacket.
    Returned synchronously to the caller. Hardware must not move until PASS is received.
    """
    # Echoes the request_id from the original IntentPacket for correlation
    request_id: str

    # The firewall's verdict
    decision: DecisionStatus

    # Human-readable explanation. Required on VETO and WARN, None on PASS.
    reason: Optional[str] = None

    # Which engine component made the decision
    source: Optional[VetoSource] = None

    # Validation pipeline wall-clock time in milliseconds. Target: < 200ms.
    latency_ms: float

    # On WARN: a token the operator must supply to override and re-submit the intent.
    # None on PASS or VETO.
    hitl_override_token: Optional[str] = None


# ─────────────────────────────────────────────
# AASLConfig — Firewall Configuration
# ─────────────────────────────────────────────

class ViamConnectionConfig(BaseModel):
    """Typed sub-model for Viam connection details. Prevents silent key-name typos."""
    address: str            # e.g., "rubik-pi.local:8080"
    api_key: str            # Viam API key
    api_key_id: str         # Viam API key ID
    arm_component_name: str = "arm"  # Name as registered in Viam RDK


class AASLConfig(BaseModel):
    """
    Top-level configuration for the Semantic Firewall Governor.
    Loaded once at server startup from environment or config file.
    """
    # Path to the YAML policy manifest (forbidden_pairs + spatial_rules)
    policy_manifest_path: str

    # Confidence floor for non-visual-injection intents (MCR Step A)
    mcr_base_threshold: float = 0.7

    # Elevated confidence requirement for VISUAL_TEXT_INJECTION source (MCR Step B)
    # Visual injections are only allowed through at a much higher bar, if at all.
    mcr_visual_injection_threshold: float = 0.99

    # Set of source modalities that are ALWAYS escalated to WARN regardless of confidence.
    # The HITL operator must approve these manually.
    # Default: visual text injections always require human review.
    mcr_always_warn_modalities: List[SourceModality] = [
        SourceModality.VISUAL_TEXT_INJECTION,
        SourceModality.UNKNOWN,
    ]

    # Enable/disable LTL temporal invariant checking.
    # Disable during early testing if RTAMT is not yet integrated.
    enable_temporal_checks: bool = True

    # Max number of recent intents to hold in the LTL history buffer.
    # Prevents unbounded memory growth. Window size for temporal rules.
    ltl_history_window: int = 50

    # Viam hardware connection details (None in software/simulation mode)
    viam_config: Optional[ViamConnectionConfig] = None
